name: Stats

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  python-tests:
    name: generate stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: stats
        run: |
          python3 freq.py

      - name: save
        run: |
          git config --global user.email "s50600822@gmail.com"
          git config --global user.name "s50600822"
          git add .
          git commit -m "save"
          git push